server:
  address: localhost
  port: 9797
  servlet:
    context-path: /
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.jiuqi.cosmos.entity
  configuration:
    mapUnderscoreToCamelCase: true
spring:
  application: 
    name: cosmos
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cosmos?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 111111
    driver-class-name:  com.mysql.cj.jdbc.Driver